### PR TITLE
Remove assumesPageView option

### PR DESCRIPTION
**Pull request by duellsy**
Removes confusion for customers who aren't immediately calling page(), and wondering why the elevio script hasn't loaded yet.

### CODE REVIEW

**Comment by duellsy** [comment]
Just looping in @hankim813 since you accepted the last PR for this project, hoping you can do the same here :)

**Comment by hankim813** [comment]
hey @duellsy thanks for the PR — I moved out of eng recently but @jlee9595 should be able to help here.

**Comment by jlee9595** [comment]
Hi @duellsy ! I believe that all that `assumesPageView` does is cause the first `page` call to be ignored, and has no effect on when the script is loaded. Would you mind providing me with a valid Elevio account id I can use to test this knowledge myself on the integration? If I end up being wrong about that then this PR looks great to me.

**Comment by duellsy** [comment]
Oh, I see. How can we have the script be loaded immediately rather than
waiting for page() to be called?

You can test with account id: konami

**Comment by jlee9595** [comment]
Hey @duellsy I'm currently looking into this and will get back to you later today

**Comment by jlee9595** [comment]
@duellsy One question I have is whether the Elevio script does some kind of `page` when it loads. The purpose of `assumesPageView` is to prevent integrations with scripts that do a `page` when they load from inaccurately recording two `page`s, one from the script loading and one from the first Segment `page` call, by causing the first Segment `page` to be dropped. If the Elevio script doesn't `page` when it loads then I'd say that you should definitely go ahead and get rid of `assumesPageView` but if it does `page` on load, then I think we should find an alternate solution to your problem here.

**Comment by jlee9595** [comment]
@duellsy Elevio is using version 2 of `analytics.js-integration` and doesn't have the following update to `assumesPageView` which came in 3.2: https://github.com/segmentio/analytics.js-integration/commit/7597a6fa0127d1cf3c670e36453866d628814df7

My final recommendation is to first update the `analytics.js-integration` dependency, but if Elevio doesn't automatically `page` on load then you should remove `assumesPageView` as well for the reasons described above.

**Comment by duellsy** [comment]
@jlee9595 ooh, ok.

Am I correct in thinking if we upgrade `analytics.js-integration` to 3.2 this will allow our script to load immediately rather than waiting for the `page` call to be made by the hosting site?

Essentially, in the example here, we'd like the elevio script to be loaded immediately, rather than waiting for the `page` call to be made (which you can simulate by clicking the button in the middle of the screen)

https://jsfiddle.net/duellsy/xcfzygcp/

Is this something that is possible, can you foresee issues with this?

**Comment by jlee9595** [comment]
@duellsy That's correct! Upgrading to 3.2 should give you what you want.

**Comment by duellsy** [comment]
Fantastic, thanks @jlee9595, just updated to 3.2 and pushed

🎉

**Review by jlee9595 — APPROVED** [review]

**Pull request merged**
